export const properties = [
  {
    id: 1,
    type: ["venta"],
    title: "Modern house in residential area",
    salePrice: 2500000,
    rentPrice: 0,
    description:
      "Spacious and bright house located in a quiet residential area.",
    propertyType: "Casa",
    info: {
      bedrooms: 3,
      bathrooms: 2,
      area: 120,
      parking: 1,
      petsAllowed: true,
      years: "15",
    },
    location: {
      address: "123 Robles St, Jardines",
      state: "Guerrero",
      city: "Acapulco",
    },
    images: [
      "https://images.pexels.com/photos/276724/pexels-photo-276724.jpeg",
      "https://example.com/img/house1_2.jpg",
      "https://example.com/img/house1_3.jpg",
    ],
    available: true,
    postedAt: "2025-06-01",
  },
  {
    id: 2,
    type: ["renta"],
    title: "Furnished downtown apartment",
    salePrice: 0,
    rentPrice: 16000,
    description:
      "Fully furnished apartment close to shops, restaurants, and transport.",
    propertyType: "Departamento",
    info: {
      bedrooms: 2,
      bathrooms: 1,
      area: 75,
      parking: 0,
      petsAllowed: false,
      years: "5",
    },
    location: {
      address: "456 Reforma Ave, Centro",
      state: "Ciudad de México",
      city: "CDMX",
    },
    images: [
      "https://images.pexels.com/photos/2724749/pexels-photo-2724749.jpeg",
      "https://images.pexels.com/photos/276724/pexels-photo-276724.jpeg",
      "https://example.com/img/apartment1.jpg",
      "https://example.com/img/apartment1_2.jpg",
      "https://example.com/img/apartment1_3.jpg",
    ],
    available: true,
    postedAt: "2025-05-20",
  },
  {
    id: 3,
    type: ["venta", "renta"],
    title: "Cozy loft with city view",
    salePrice: 2800000,
    rentPrice: 19000,
    description:
      "Minimalist loft with panoramic views and lots of natural light.",
    propertyType: "Loft",
    info: {
      bedrooms: 1,
      bathrooms: 1,
      area: 60,
      parking: 1,
      petsAllowed: true,
      years: "new",
    },
    location: {
      address: "78 Lomas Verdes",
      state: "Estado de México",
      city: "Naucalpan",
    },
    images: [
      "https://images.pexels.com/photos/276724/pexels-photo-276724.jpeg",
      "https://example.com/img/loft1.jpg",
      "https://example.com/img/loft1_2.jpg",
      "https://example.com/img/loft1_3.jpg",
    ],
    available: true,
    postedAt: "2025-06-10",
  },
  {
    id: 4,
    type: ["venta"],
    title: "Luxury villa with private pool",
    salePrice: 6500000,
    rentPrice: 0,
    description:
      "Exclusive villa with a private pool, garden, and security system.",
    propertyType: "Villa",
    info: {
      bedrooms: 4,
      bathrooms: 4,
      area: 300,
      parking: 2,
      petsAllowed: true,
      years: "10",
    },
    location: {
      address: "99 Ocean View Rd",
      state: "Quintana Roo",
      city: "Cancún",
    },
    images: [
      "https://images.pexels.com/photos/2724749/pexels-photo-2724749.jpeg",
      "https://example.com/img/villa1.jpg",
      "https://example.com/img/villa1_2.jpg",
      "https://example.com/img/villa1_3.jpg",
    ],
    available: false,
    postedAt: "2025-04-18",
  },
  {
    id: 5,
    type: ["renta"],
    title: "Studio apartment near university",
    salePrice: 0,
    rentPrice: 9500,
    description:
      "Compact and affordable studio ideal for students or young professionals.",
    propertyType: "Estudio",
    info: {
      bedrooms: 1,
      bathrooms: 1,
      area: 35,
      parking: 0,
      petsAllowed: false,
      years: "new",
    },
    location: {
      address: "55 University St",
      state: "Ciudad de México",
      city: "Coyoacán",
    },
    images: [
      "https://images.pexels.com/photos/2635038/pexels-photo-2635038.jpeg",
      "https://example.com/img/studio1.jpg",
      "https://example.com/img/studio1_2.jpg",
      "https://example.com/img/studio1_3.jpg",
    ],
    available: true,
    postedAt: "2025-06-14",
  },
];
